const Router=require("express").Router()
const cors = require("cors")

Router.use(cors())

const usercontrol=require("./controllers/userControl")
const worldcontrol=require("./controllers/worldControl")
const reportscontrol=require("./controllers/reportsControl")
const mailscontrol=require("./controllers/mailsControl")
const unitcontrol=require("./controllers/unitControl")
const buildcontrol=require("./controllers/buildControl")
const diplomacycontrol=require("./controllers/diplomacyControl")
//const admincontrol=require("./controllers/adminControl")
Router.get('/',usercontrol.connection)
Router.post('/register',usercontrol.register)
Router.post('/login',usercontrol.login)
Router.post('/world',worldcontrol.start)
Router.post('/checkToken',usercontrol.apiMustBeLoggedIn)
Router.post('/updateStatus',usercontrol.update)
Router.post('/reports',reportscontrol.start)
Router.post('/mails',mailscontrol.start)
Router.post('/report',reportscontrol.displayReport)
Router.post('/deletereport',reportscontrol.delete)
Router.post('/mail',mailscontrol.displayMail)
Router.post('/sendmail',mailscontrol.sendM)
Router.post('/deletemail',mailscontrol.delete)
Router.post('/recruit',unitcontrol.start)
Router.post('/build',buildcontrol.start)
Router.post('/getgold',usercontrol.getGold)
Router.post('/getunits',usercontrol.getUnits)
Router.post('/players',usercontrol.players)
Router.post('/playersearch',usercontrol.playersearch)
Router.post('/diplomacy',diplomacycontrol.start)
Router.post('/attack',unitcontrol.war)
Router.post('/aid',unitcontrol.aid)
//Router.post('/getunits',usercontrol.getUnits)
//Router.get('/order/:id',usercontrol.apiMustBeLoggedIn,cartcontrol.apiOrder)
module.exports=Router