const Router=require("express").Router()
const cors = require("cors")

Router.use(cors())

const usercontrol=require("./controllers/userControl")
const providerscontrol=require("./controllers/providersControl")
const worldcontrol=require("./controllers/worldControl")
const worldactionscontrol=require("./controllers/worldActionsControl")
const reportscontrol=require("./controllers/reportsControl")
const mailscontrol=require("./controllers/mailsControl")
//const unitcontrol=require("./controllers/unitControl")
const buildcontrol=require("./controllers/buildControl")
const marketcontrol=require("./controllers/marketControl")
const bribecontrol=require("./controllers/bribeControl")
//const diplomacycontrol=require("./controllers/diplomacyControl")
const admincontrol=require("./controllers/adminControl")
const bonuscontrol=require("./controllers/bonusControl")

Router.post('/loginadmin',admincontrol.login)
Router.post('/checkTokenadmin',admincontrol.apiMustBeLoggedIn)
Router.post('/grabDataadmin',admincontrol.grabData)
Router.post('/visitor',usercontrol.visitor)

Router.post('/register',usercontrol.register)
Router.post('/login',usercontrol.login)
Router.post('/providers',providerscontrol.login)
Router.post('/forget',usercontrol.forget)
Router.post('/reset',usercontrol.reset)
//Router.get('/setup',usercontrol.setup)
Router.post('/world',worldcontrol.start)
Router.post('/reveal',worldcontrol.reveal)
Router.post('/explore',worldactionscontrol.explore)
Router.post('/exploreupdate',worldactionscontrol.exploreUpdate)
Router.get('/test',worldactionscontrol.test)
Router.post('/attack',worldactionscontrol.attack)
Router.post('/fortress',worldactionscontrol.fortress)
Router.post('/rebuild',worldactionscontrol.rebuild)
Router.post('/checkToken',usercontrol.apiMustBeLoggedIn)
Router.post('/grabData',usercontrol.grabData)
//Router.post('/updateStatus',usercontrol.update)
Router.post('/reports',reportscontrol.start)
Router.post('/report',reportscontrol.displayReport)
Router.post('/deleteSelectedR',reportscontrol.deleteSelected)
Router.post('/deleteR',reportscontrol.delete)
Router.post('/deleteAllR',reportscontrol.deleteAll)
Router.post('/mails',mailscontrol.start)
Router.post('/mail',mailscontrol.displayMail)
Router.post('/sendmail',mailscontrol.sendMail)
Router.post('/sendreply',mailscontrol.sendReply)
Router.post('/deleteSelectedM',mailscontrol.deleteSelected)
Router.post('/deleteM',mailscontrol.delete)
Router.post('/deleteAllM',mailscontrol.deleteAll)
Router.post('/bribe',bribecontrol.stepOne)


//Router.post('/report',reportscontrol.displayReport)
//Router.post('/deletereport',reportscontrol.delete)
//Router.post('/recruit',unitcontrol.start)
Router.post('/market',marketcontrol.start)
Router.post('/buyunit',marketcontrol.buy)
Router.post('/sellunit',marketcontrol.sell)
Router.post('/upgrade',marketcontrol.upgrade)
Router.post('/build',buildcontrol.start)
Router.post('/getgold',usercontrol.getGold)
Router.post('/getunits',usercontrol.getUnits)
Router.post('/bonus',bonuscontrol.getBonus)
Router.post('/vote',bonuscontrol.vote)
Router.post('/collect',bonuscontrol.collect)

//Router.post('/players',usercontrol.players)
//Router.post('/playersearch',usercontrol.playersearch)
//Router.post('/diplomacy',diplomacycontrol.start)
//Router.post('/attack',unitcontrol.war)
//Router.post('/aid',unitcontrol.aid)
//Router.post('/getunits',usercontrol.getUnits)
//Router.get('/order/:id',usercontrol.apiMustBeLoggedIn,cartcontrol.apiOrder)
module.exports=Router